import { getMonthName, IMonth } from "./Months"
import { isLeapYear } from "./Years"

interface INameDay {
  date: IMonth
  names: Array<string>
}

export const NAME_DAYS: ReadonlyArray<INameDay> = [
	// Január
	{ date: { month: 'Január', days: 1 }, names: ['Alpár', 'Fruzsina', 'Bazil'] },
	{ date: { month: 'Január', days: 2 }, names: ['Ábel', 'Gergely', 'Vazul'] },
	{ date: { month: 'Január', days: 3 }, names: ['Genovéva', 'Gyöngyvér', 'Benjámin', 'Dzsenifer'] },
	{ date: { month: 'Január', days: 4 }, names: ['Titusz', 'Leona', 'Angéla'] },
	{ date: { month: 'Január', days: 5 }, names: ['Simon', 'Emília'] },
	{ date: { month: 'Január', days: 6 }, names: ['Gáspár', 'Menyhért', 'Boldizsár'] },
	{ date: { month: 'Január', days: 7 }, names: ['Attila', 'Etele', 'Ramóna', 'Rajmund', 'Bálint'] },
	{ date: { month: 'Január', days: 8 }, names: ['Gyöngyvér', 'Keve', 'Szeverin', 'Szörény'] },
	{ date: { month: 'Január', days: 9 }, names: ['Marcell', 'Juliánusz'] },
	{ date: { month: 'Január', days: 10 }, names: ['Melánia', 'Vilmos', 'Vilma'] },
	{ date: { month: 'Január', days: 11 }, names: ['Ágota', 'Honoráta'] },
	{ date: { month: 'Január', days: 12 }, names: ['Ernő', 'Erneszta', 'Tatjána'] },
	{ date: { month: 'Január', days: 13 }, names: ['Veronika', 'Csongor', 'Yvett'] },
	{ date: { month: 'Január', days: 14 }, names: ['Bódog', 'Félix'] },
	{ date: { month: 'Január', days: 15 }, names: ['Lóránt', 'Loránd', 'Pál'] },
	{ date: { month: 'Január', days: 16 }, names: ['Gusztáv', 'Marcell'] },
	{ date: { month: 'Január', days: 17 }, names: ['Antal', 'Antónia'] },
	{ date: { month: 'Január', days: 18 }, names: ['Margit', 'Piroska'] },
	{ date: { month: 'Január', days: 19 }, names: ['Sára', 'Márta', 'Márió'] },
	{ date: { month: 'Január', days: 20 }, names: ['Fábián', 'Sebestyén'] },
	{ date: { month: 'Január', days: 21 }, names: ['Ágnes', 'Agnéta'] },
	{ date: { month: 'Január', days: 22 }, names: ['Vince', 'Artúr'] },
	{ date: { month: 'Január', days: 23 }, names: ['Zelma', 'Rajmund', 'Emerencia', 'Emese'] },
	{ date: { month: 'Január', days: 24 }, names: ['Timót', 'Ferenc'] },
	{ date: { month: 'Január', days: 25 }, names: ['Pál', 'Henrik'] },
	{ date: { month: 'Január', days: 26 }, names: ['Vanda', 'Paula', 'Timóteusz'] },
	{ date: { month: 'Január', days: 27 }, names: ['Angéla', 'Angelika'] },
	{ date: { month: 'Január', days: 28 }, names: ['Károly', 'Karola', 'Tamás'] },
	{ date: { month: 'Január', days: 29 }, names: ['Adél', 'Valér'] },
	{ date: { month: 'Január', days: 30 }, names: ['Martina', 'Gerda', 'Jácinta'] },
	{ date: { month: 'Január', days: 31 }, names: ['Marcella', 'János'] },

	// Február
	{ date: { month: 'Február', days: 1 }, names: ['Ignác', 'Brigitta', 'Kincső', 'Renátó'] },
	{ date: { month: 'Február', days: 2 }, names: ['Karolina', 'Karola', 'Aida'] },
	{ date: { month: 'Február', days: 3 }, names: ['Balázs', 'Oszkár', 'Celerina'] },
	{ date: { month: 'Február', days: 4 }, names: ['Ráhel', 'Csenge', 'Veronika', 'András'] },
	{ date: { month: 'Február', days: 5 }, names: ['Ágota', 'Ingrid', 'Etelka', 'Léda'] },
	{ date: { month: 'Február', days: 6 }, names: ['Dorottya', 'Dóra', 'Pál'] },
	{ date: { month: 'Február', days: 7 }, names: ['Tódor', 'Rómeó', 'Richárd'] },
	{ date: { month: 'Február', days: 8 }, names: ['Aranka', 'Jeromos'] },
	{ date: { month: 'Február', days: 9 }, names: ['Abigél', 'Alex', 'Apollónia'] },
	{ date: { month: 'Február', days: 10 }, names: ['Elvira'] },
	{ date: { month: 'Február', days: 11 }, names: ['Bertold', 'Marietta'] },
	{ date: { month: 'Február', days: 12 }, names: ['Lívia', 'Lídia', 'Eulália'] },
	{ date: { month: 'Február', days: 13 }, names: ['Ella', 'Linda', 'Levente', 'Katalin'] },
	{ date: { month: 'Február', days: 14 }, names: ['Bálint', 'Valentin', 'Cirill', 'Metód'] },
	{ date: { month: 'Február', days: 15 }, names: ['Kolos', 'Györgyi', 'Georgina'] },
	{ date: { month: 'Február', days: 16 }, names: ['Julianna', 'Lilla', 'Filippa'] },
	{ date: { month: 'Február', days: 17 }, names: ['Donát'] },
	{ date: { month: 'Február', days: 18 }, names: ['Bernadett', 'Simon', 'Zenkő'] },
	{ date: { month: 'Február', days: 19 }, names: ['Zsuzsanna', 'Eliza', 'Konrád'] },
	{ date: { month: 'Február', days: 20 }, names: ['Aladár', 'Álmos', 'Leó'] },
	{ date: { month: 'Február', days: 21 }, names: ['Eleonóra', 'Zelmira', 'Péter'] },
	{ date: { month: 'Február', days: 22 }, names: ['Gerzson', 'Margit', 'Zétény'] },
	{ date: { month: 'Február', days: 23 }, names: ['Alfréd', 'Polikárp', 'Mirtill'] },
	{ date: { month: 'Február', days: 24 }, names: ['Mátyás', 'Jázmin'] },
	{ date: { month: 'Február', days: 25 }, names: ['Géza', 'Cézár', 'Vanda'] },
	{ date: { month: 'Február', days: 26 }, names: ['Viktor', 'Győző'] },
	{ date: { month: 'Február', days: 27 }, names: ['Ákos', 'Bátor', 'Gábor', 'Edina'] },
	{ date: { month: 'Február', days: 28 }, names: ['Elemér', 'Oszvald', 'Román'] },

	// Március
	{ date: { month: 'Március', days: 1 }, names: ['Albin', 'Albina', 'Leonita'] },
	{ date: { month: 'Március', days: 2 }, names: ['Lujza', 'Ágnes', 'Henrik', 'Magor'] },
	{ date: { month: 'Március', days: 3 }, names: ['Kornélia', 'Kunigunda', 'Frigyes'] },
	{ date: { month: 'Március', days: 4 }, names: ['Kázmér', 'Lúciusz', 'Zorán'] },
	{ date: { month: 'Március', days: 5 }, names: ['Adorján', 'Adrián'] },
	{ date: { month: 'Március', days: 6 }, names: ['Leonóra', 'Inez', 'Koletta'] },
	{ date: { month: 'Március', days: 7 }, names: ['Tamás', 'Perpétua', 'Felicitász'] },
	{ date: { month: 'Március', days: 8 }, names: ['János', 'Zoltán', 'Apolka'] },
	{ date: { month: 'Március', days: 9 }, names: ['Franciska', 'Fanni'] },
	{ date: { month: 'Március', days: 10 }, names: ['Ildikó', 'Emil', 'Gusztáv'] },
	{ date: { month: 'Március', days: 11 }, names: ['Szilárd', 'Tímea', 'Konstantin'] },
	{ date: { month: 'Március', days: 12 }, names: ['Gergely', 'Maximilián'] },
	{ date: { month: 'Március', days: 13 }, names: ['Krisztián', 'Ajtony', 'Egyed', 'Patrícia'] },
	{ date: { month: 'Március', days: 14 }, names: ['Matild', 'Matilda', 'Trilla'] },
	{ date: { month: 'Március', days: 15 }, names: ['Kristóf', 'Kelemen'] },
	{ date: { month: 'Március', days: 16 }, names: ['Henrietta', 'Herbert'] },
	{ date: { month: 'Március', days: 17 }, names: ['Gertrúd', 'Patrik'] },
	{ date: { month: 'Március', days: 18 }, names: ['Sándor', 'Ede', 'Cirill'] },
	{ date: { month: 'Március', days: 19 }, names: ['József', 'Bánk'] },
	{ date: { month: 'Március', days: 20 }, names: ['Klaudia', 'Alexandra'] },
	{ date: { month: 'Március', days: 21 }, names: ['Benedek', 'Bence', 'Miklós'] },
	{ date: { month: 'Március', days: 22 }, names: ['Beáta', 'Izolda', 'Lea'] },
	{ date: { month: 'Március', days: 23 }, names: ['Emőke', 'Botond', 'Ottó', 'Kartal'] },
	{ date: { month: 'Március', days: 24 }, names: ['Gábor', 'Karina'] },
	{ date: { month: 'Március', days: 25 }, names: ['Irén', 'Írisz', 'Lúcia'] },
	{ date: { month: 'Március', days: 26 }, names: ['Emánuel', 'Emánuéla', 'Lara', 'Larissza', 'Árpád'] },
	{ date: { month: 'Március', days: 27 }, names: ['Hajnalka', 'Lídia', 'Auguszta'] },
	{ date: { month: 'Március', days: 28 }, names: ['Gedeon', 'Johanna'] },
	{ date: { month: 'Március', days: 29 }, names: ['Auguszta', 'Bertold'] },
	{ date: { month: 'Március', days: 30 }, names: ['Zalán'] },
	{ date: { month: 'Március', days: 31 }, names: ['Árpád', 'Benjámin', 'Benő'] },

	// Április
	{ date: { month: 'Április', days: 1 }, names: ['Hugó', 'Agád'] },
	{ date: { month: 'Április', days: 2 }, names: ['Áron', 'Ferenc'] },
	{ date: { month: 'Április', days: 3 }, names: ['Buda', 'Richárd', 'Hóvirág', 'Indira'] },
	{ date: { month: 'Április', days: 4 }, names: ['Izidor'] },
	{ date: { month: 'Április', days: 5 }, names: ['Vince', 'Irén', 'Teodóra'] },
	{ date: { month: 'Április', days: 6 }, names: ['Vilmos', 'Bíborka', 'Taksony', 'Celesztin'] },
	{ date: { month: 'Április', days: 7 }, names: ['Herman', 'János'] },
	{ date: { month: 'Április', days: 8 }, names: ['Dénes', 'Valér', 'Valter'] },
	{ date: { month: 'Április', days: 9 }, names: ['Erhard', 'Ákos', 'Döme'] },
	{ date: { month: 'Április', days: 10 }, names: ['Zsolt', 'Ezékiel'] },
	{ date: { month: 'Április', days: 11 }, names: ['Leó', 'Szaniszló', 'Glória'] },
	{ date: { month: 'Április', days: 12 }, names: ['Gyula', 'Baldvin', 'Sába', 'Nara'] },
	{ date: { month: 'Április', days: 13 }, names: ['Ida', 'Márton', 'Hermina'] },
	{ date: { month: 'Április', days: 14 }, names: ['Tibor'] },
	{ date: { month: 'Április', days: 15 }, names: ['Anasztázia', 'Tas', 'Oktávia'] },
	{ date: { month: 'Április', days: 16 }, names: ['Csongor', 'Bernadett'] },
	{ date: { month: 'Április', days: 17 }, names: ['Rudolf', 'Izidóra'] },
	{ date: { month: 'Április', days: 18 }, names: ['Andrea', 'Ilma', 'Apolló', 'Aladár'] },
	{ date: { month: 'Április', days: 19 }, names: ['Emma', 'Malvin', 'Zseraldina'] },
	{ date: { month: 'Április', days: 20 }, names: ['Tivadar', 'Tihamér', 'Töhötöm'] },
	{ date: { month: 'Április', days: 21 }, names: ['Konrád', 'Zelmira', 'Anzelm'] },
	{ date: { month: 'Április', days: 22 }, names: ['Csilla', 'Noémi', 'Kájusz', 'Noé'] },
	{ date: { month: 'Április', days: 23 }, names: ['Béla', 'Adalbert'] },
	{ date: { month: 'Április', days: 24 }, names: ['György', 'Fidél', 'Debóra'] },
	{ date: { month: 'Április', days: 25 }, names: ['Márk', 'Ányos', 'Mohamed'] },
	{ date: { month: 'Április', days: 26 }, names: ['Ervin', 'Klétusz'] },
	{ date: { month: 'Április', days: 27 }, names: ['Zita', 'Mariann', 'Anasztáz'] },
	{ date: { month: 'Április', days: 28 }, names: ['Valéria', 'Péter'] },
	{ date: { month: 'Április', days: 29 }, names: ['Péter', 'Katalin', 'Roberta'] },
	{ date: { month: 'Április', days: 30 }, names: ['Katalin', 'Kitti', 'Zsófia', 'Piusz'] },

	// Május
	{ date: { month: 'Május', days: 1 }, names: ['Fülöp', 'Jakab', 'Zsaklin', 'Jefte', 'József'] },
	{ date: { month: 'Május', days: 2 }, names: ['Zsigmond', 'Atanáz', 'Zoé'] },
	{ date: { month: 'Május', days: 3 }, names: ['Tímea', 'Irma', 'Jakab', 'Fülöp'] },
	{ date: { month: 'Május', days: 4 }, names: ['Mónika', 'Flórián'] },
	{ date: { month: 'Május', days: 5 }, names: ['Györgyi', 'Irén'] },
	{ date: { month: 'Május', days: 6 }, names: ['Ivett', 'Frida', 'Judit', 'Yvett'] },
	{ date: { month: 'Május', days: 7 }, names: ['Gizella', 'Gusztáv', 'Bendegúz', 'Gália'] },
	{ date: { month: 'Május', days: 8 }, names: ['Mihály', 'Győző'] },
	{ date: { month: 'Május', days: 9 }, names: ['Gergely', 'Katinka', 'Alberta', 'Édua'] },
	{ date: { month: 'Május', days: 10 }, names: ['Ármin', 'Pálma', 'Izidor'] },
	{ date: { month: 'Május', days: 11 }, names: ['Ferenc', 'Sára'] },
	{ date: { month: 'Május', days: 12 }, names: ['Pongrác'] },
	{ date: { month: 'Május', days: 13 }, names: ['Szervác', 'Imola', 'Imelda'] },
	{ date: { month: 'Május', days: 14 }, names: ['Bonifác', 'Gyöngyi'] },
	{ date: { month: 'Május', days: 15 }, names: ['Zsófia', 'Szonja', 'Döníz'] },
	{ date: { month: 'Május', days: 16 }, names: ['Mózes', 'Botond', 'János'] },
	{ date: { month: 'Május', days: 17 }, names: ['Paszkál', 'Ditmár', 'Rezeda'] },
	{ date: { month: 'Május', days: 18 }, names: ['Erik', 'Alexandra', 'János'] },
	{ date: { month: 'Május', days: 19 }, names: ['Ivó', 'Iván', 'Milán'] },
	{ date: { month: 'Május', days: 20 }, names: ['Bernát', 'Bernardin', 'Felícia'] },
	{ date: { month: 'Május', days: 21 }, names: ['Konstantin', 'András'] },
	{ date: { month: 'Május', days: 22 }, names: ['Júlia', 'Rita', 'Emil'] },
	{ date: { month: 'Május', days: 23 }, names: ['Dezső', 'Vilmos', 'Renáta'] },
	{ date: { month: 'Május', days: 24 }, names: ['Eszter', 'Eliza', 'Vanessza'] },
	{ date: { month: 'Május', days: 25 }, names: ['Orbán', 'Gergely'] },
	{ date: { month: 'Május', days: 26 }, names: ['Fülöp', 'Evelin'] },
	{ date: { month: 'Május', days: 27 }, names: ['Hella', 'Pelbárt', 'Ágoston'] },
	{ date: { month: 'Május', days: 28 }, names: ['Emil', 'Csanád', 'Vilmos'] },
	{ date: { month: 'Május', days: 29 }, names: ['Magdolna', 'Magda', 'Ervin', 'Léna'] },
	{ date: { month: 'Május', days: 30 }, names: ['Janka', 'Zsanett', 'Johanna', 'Nándor'] },
	{ date: { month: 'Május', days: 31 }, names: ['Angéla', 'Petronella'] },

	// Június
	{ date: { month: 'Június', days: 1 }, names: ['Tünde', 'Jusztinusz'] },
	{ date: { month: 'Június', days: 2 }, names: ['Kármen', 'Anita', 'Péter', 'Marcellinusz'] },
	{ date: { month: 'Június', days: 3 }, names: ['Klotild', 'Cecília', 'Károly', 'Kevin'] },
	{ date: { month: 'Június', days: 4 }, names: ['Bulcsú', 'Kerény', 'Kerubin'] },
	{ date: { month: 'Június', days: 5 }, names: ['Frézia', 'Zenke', 'Fatime', 'Fatima', 'Bonifác'] },
	{ date: { month: 'Június', days: 6 }, names: ['Norbert', 'Norberta', 'Cintia'] },
	{ date: { month: 'Június', days: 7 }, names: ['Róbert', 'Robertina', 'Arianna', 'Fülöp', 'Roberta'] },
	{ date: { month: 'Június', days: 8 }, names: ['Medárd', 'Helga'] },
	{ date: { month: 'Június', days: 9 }, names: ['Félix', 'Előd', 'Annamária', 'Annabella'] },
	{ date: { month: 'Június', days: 10 }, names: ['Margit', 'Gréta'] },
	{ date: { month: 'Június', days: 11 }, names: ['Barnabás', 'Barangó'] },
	{ date: { month: 'Június', days: 12 }, names: ['Villő', 'Orfeusz', 'Adelaida'] },
	{ date: { month: 'Június', days: 13 }, names: ['Antal', 'Anett'] },
	{ date: { month: 'Június', days: 14 }, names: ['Vazul', 'Elizeus', 'Herta'] },
	{ date: { month: 'Június', days: 15 }, names: ['Jolán', 'Vid', 'Viola', 'Ariana'] },
	{ date: { month: 'Június', days: 16 }, names: ['Jusztin', 'Jusztina', 'Auréliusz'] },
	{ date: { month: 'Június', days: 17 }, names: ['Laura', 'Alida', 'Alina', 'Szabolcs', 'Adolf', 'Bató'] },
	{ date: { month: 'Június', days: 18 }, names: ['Arnold', 'Levente', 'Doloróza'] },
	{ date: { month: 'Június', days: 19 }, names: ['Gyárfás', 'Romuald', 'Azurea'] },
	{ date: { month: 'Június', days: 20 }, names: ['Rafael', 'Dina'] },
	{ date: { month: 'Június', days: 21 }, names: ['Alajos', 'Leila'] },
	{ date: { month: 'Június', days: 22 }, names: ['Paulina', 'Tamás'] },
	{ date: { month: 'Június', days: 23 }, names: ['Zoltán', 'Szultána'] },
	{ date: { month: 'Június', days: 24 }, names: ['János', 'Iván'] },
	{ date: { month: 'Június', days: 25 }, names: ['Vilmos', 'Viola', 'Vilma'] },
	{ date: { month: 'Június', days: 26 }, names: ['János', 'Pál', 'Cirill'] },
	{ date: { month: 'Június', days: 27 }, names: ['László', 'Sámson'] },
	{ date: { month: 'Június', days: 28 }, names: ['Levente', 'Irén', 'Iréneusz'] },
	{ date: { month: 'Június', days: 29 }, names: ['Péter', 'Pál', 'Emőke', 'Judit', 'Petra', 'Szulamit', 'Ivett'] },
	{ date: { month: 'Június', days: 30 }, names: ['Pál'] },

	// Július
	{ date: { month: 'Július', days: 1 }, names: ['Tihamér', 'Annamária', 'Olivér', 'Áron'] },
	{ date: { month: 'Július', days: 2 }, names: ['Ottó'] },
	{ date: { month: 'Július', days: 3 }, names: ['Kornél', 'Soma', 'Tamás'] },
	{ date: { month: 'Július', days: 4 }, names: ['Ulrik', 'Erzsébet'] },
	{ date: { month: 'Július', days: 5 }, names: ['Emese', 'Sarolta', 'Lotti', 'Antal', 'Nara'] },
	{ date: { month: 'Július', days: 6 }, names: ['Csaba', 'Mária'] },
	{ date: { month: 'Július', days: 7 }, names: ['Apollónia', 'Vilibald', 'Bene'] },
	{ date: { month: 'Július', days: 8 }, names: ['Ellák', 'Edgár', 'Eperke'] },
	{ date: { month: 'Július', days: 9 }, names: ['Lukrécia', 'Veronika', 'Hajnalka'] },
	{ date: { month: 'Július', days: 10 }, names: ['Amália', 'Melina', 'Engelbert', 'Ulrika'] },
	{ date: { month: 'Július', days: 11 }, names: ['Nóra', 'Lili', 'Nelli', 'Benedek'] },
	{ date: { month: 'Július', days: 12 }, names: ['Izabella', 'Dalma', 'Eleonóra'] },
	{ date: { month: 'Július', days: 13 }, names: ['Jenő', 'Henrik'] },
	{ date: { month: 'Július', days: 14 }, names: ['Örs', 'Stella', 'Kamil'] },
	{ date: { month: 'Július', days: 15 }, names: ['Örkény', 'Henrik', 'Roland', 'Bonaventúra'] },
	{ date: { month: 'Július', days: 16 }, names: ['Valter', 'Irma'] },
	{ date: { month: 'Július', days: 17 }, names: ['Endre', 'Elek', 'András'] },
	{ date: { month: 'Július', days: 18 }, names: ['Szömér', 'Frigyes', 'Milla', 'Hedvig', 'Mirkó'] },
	{ date: { month: 'Július', days: 19 }, names: ['Emília'] },
	{ date: { month: 'Július', days: 20 }, names: ['Illés', 'Margaréta'] },
	{ date: { month: 'Július', days: 21 }, names: ['Dániel', 'Daniella', 'Lőrinc'] },
	{ date: { month: 'Július', days: 22 }, names: ['Magdolna', 'Mária', 'Magda', 'Nara'] },
	{ date: { month: 'Július', days: 23 }, names: ['Lenke', 'Brigitta', 'Apollinár'] },
	{ date: { month: 'Július', days: 24 }, names: ['Kinga', 'Kunigunda', 'Kincső', 'Krisztina'] },
	{ date: { month: 'Július', days: 25 }, names: ['Kristóf', 'Jakab'] },
	{ date: { month: 'Július', days: 26 }, names: ['Anna', 'Anikó', 'Joakim'] },
	{ date: { month: 'Július', days: 27 }, names: ['Olga', 'Liliána', 'Natália', 'Pantaleon'] },
	{ date: { month: 'Július', days: 28 }, names: ['Szabolcs', 'Alina', 'Ince', 'Győző'] },
	{ date: { month: 'Július', days: 29 }, names: ['Márta', 'Flóra'] },
	{ date: { month: 'Július', days: 30 }, names: ['Judit', 'Xénia', 'Péter'] },
	{ date: { month: 'Július', days: 31 }, names: ['Oszkár', 'Ignác', 'Bató'] },

	// Augusztus
	{ date: { month: 'Augusztus', days: 1 }, names: ['Boglárka', 'Nimród', 'Alfonz'] },
	{ date: { month: 'Augusztus', days: 2 }, names: ['Lehel'] },
	{ date: { month: 'Augusztus', days: 3 }, names: ['Hermina', 'Lídia', 'Kamélia', 'Kíra', 'Mirtill'] },
	{ date: { month: 'Augusztus', days: 4 }, names: ['Domonkos', 'Dominik', 'János', 'Dominika'] },
	{ date: { month: 'Augusztus', days: 5 }, names: ['Krisztina'] },
	{ date: { month: 'Augusztus', days: 6 }, names: ['Berta', 'Bettina'] },
	{ date: { month: 'Augusztus', days: 7 }, names: ['Ibolya'] },
	{ date: { month: 'Augusztus', days: 8 }, names: ['László', 'Domonkos'] },
	{ date: { month: 'Augusztus', days: 9 }, names: ['Emőd', 'Román'] },
	{ date: { month: 'Augusztus', days: 10 }, names: ['Lőrinc', 'Blanka', 'Csilla'] },
	{ date: { month: 'Augusztus', days: 11 }, names: ['Zsuzsanna', 'Tiborc', 'Klára'] },
	{ date: { month: 'Augusztus', days: 12 }, names: ['Klára', 'Hilária', 'Diána'] },
	{ date: { month: 'Augusztus', days: 13 }, names: ['Ipoly', 'Ince', 'Vitália'] },
	{ date: { month: 'Augusztus', days: 14 }, names: ['Marcell', 'Maximilián'] },
	{ date: { month: 'Augusztus', days: 15 }, names: ['Mária'] },
	{ date: { month: 'Augusztus', days: 16 }, names: ['Ábrahám', 'Rókus'] },
	{ date: { month: 'Augusztus', days: 17 }, names: ['Jácint', 'Réka', 'Hetény'] },
	{ date: { month: 'Augusztus', days: 18 }, names: ['Ilona', 'Rajnald'] },
	{ date: { month: 'Augusztus', days: 19 }, names: ['Huba', 'Marián', 'Emília'] },
	{ date: { month: 'Augusztus', days: 20 }, names: ['István', 'Bernát'] },
	{ date: { month: 'Augusztus', days: 21 }, names: ['Sámuel', 'Hajna', 'Piusz'] },
	{ date: { month: 'Augusztus', days: 22 }, names: ['Menyhért', 'Mirjam'] },
	{ date: { month: 'Augusztus', days: 23 }, names: ['Bence', 'Róza', 'Szidónia'] },
	{ date: { month: 'Augusztus', days: 24 }, names: ['Bertalan', 'Aliz', 'Detre'] },
	{ date: { month: 'Augusztus', days: 25 }, names: ['Lajos', 'Patrícia'] },
	{ date: { month: 'Augusztus', days: 26 }, names: ['Izsó', 'Tália', 'Natália', 'Zamfira'] },
	{ date: { month: 'Augusztus', days: 27 }, names: ['Gáspár', 'Mónika'] },
	{ date: { month: 'Augusztus', days: 28 }, names: ['Ágoston', 'Mózes'] },
	{ date: { month: 'Augusztus', days: 29 }, names: ['Beatrix', 'Erna'] },
	{ date: { month: 'Augusztus', days: 30 }, names: ['Rózsa', 'Félix', 'Letícia'] },
	{ date: { month: 'Augusztus', days: 31 }, names: ['Erika', 'Bella', 'Arisztid'] },

	// Szeptember
	{ date: { month: 'Szeptember', days: 1 }, names: ['Egyed', 'Egon', 'Noémi', 'Tamara'] },
	{ date: { month: 'Szeptember', days: 2 }, names: ['Rebeka', 'Dorina', 'Renáta', 'Ingrid', 'István', 'Axel'] },
	{ date: { month: 'Szeptember', days: 3 }, names: ['Hilda', 'Gergely'] },
	{ date: { month: 'Szeptember', days: 4 }, names: ['Rozália', 'Róza', 'Ida'] },
	{ date: { month: 'Szeptember', days: 5 }, names: ['Viktor', 'Lőrinc', 'Ofélia'] },
	{ date: { month: 'Szeptember', days: 6 }, names: ['Zakariás', 'Beáta', 'Brájen'] },
	{ date: { month: 'Szeptember', days: 7 }, names: ['Regina'] },
	{ date: { month: 'Szeptember', days: 8 }, names: ['Mária', 'Adrienn'] },
	{ date: { month: 'Szeptember', days: 9 }, names: ['Ádám', 'Péter'] },
	{ date: { month: 'Szeptember', days: 10 }, names: ['Nikolett', 'Hunor', 'Miklós'] },
	{ date: { month: 'Szeptember', days: 11 }, names: ['Teodóra', 'Jácint', 'Igor', 'Helga'] },
	{ date: { month: 'Szeptember', days: 12 }, names: ['Mária', 'Irma'] },
	{ date: { month: 'Szeptember', days: 13 }, names: ['Kornél', 'János'] },
	{ date: { month: 'Szeptember', days: 14 }, names: ['Szeréna', 'Roxána'] },
	{ date: { month: 'Szeptember', days: 15 }, names: ['Enikő', 'Melitta'] },
	{ date: { month: 'Szeptember', days: 16 }, names: ['Edit', 'Ciprián'] },
	{ date: { month: 'Szeptember', days: 17 }, names: ['Zsófia', 'Róbert'] },
	{ date: { month: 'Szeptember', days: 18 }, names: ['Diána', 'József'] },
	{ date: { month: 'Szeptember', days: 19 }, names: ['Vilhelmina', 'Januáriusz', 'Dorián'] },
	{ date: { month: 'Szeptember', days: 20 }, names: ['Friderika'] },
	{ date: { month: 'Szeptember', days: 21 }, names: ['Máté', 'Mirella', 'Jónás'] },
	{ date: { month: 'Szeptember', days: 22 }, names: ['Móric', 'Tamás'] },
	{ date: { month: 'Szeptember', days: 23 }, names: ['Tekla', 'Líviusz', 'Ila', 'Nara'] },
	{ date: { month: 'Szeptember', days: 24 }, names: ['Gellért', 'Gerda', 'Mercédesz'] },
	{ date: { month: 'Szeptember', days: 25 }, names: ['Eufrozina', 'Kende'] },
	{ date: { month: 'Szeptember', days: 26 }, names: ['Jusztina', 'Kozma', 'Damján'] },
	{ date: { month: 'Szeptember', days: 27 }, names: ['Adalbert', 'Vince'] },
	{ date: { month: 'Szeptember', days: 28 }, names: ['Vencel', 'Salamon'] },
	{ date: { month: 'Szeptember', days: 29 }, names: ['Mihály', 'Gábor', 'Rafael', 'Mirabella'] },
	{ date: { month: 'Szeptember', days: 30 }, names: ['Jeromos', 'Honória', 'Hunor'] },

	// Október
	{ date: { month: 'Október', days: 1 }, names: ['Malvin', 'Teréz'] },
	{ date: { month: 'Október', days: 2 }, names: ['Petra', 'Örs'] },
	{ date: { month: 'Október', days: 3 }, names: ['Helga', 'Évald'] },
	{ date: { month: 'Október', days: 4 }, names: ['Ferenc', 'Hajnalka'] },
	{ date: { month: 'Október', days: 5 }, names: ['Aurél', 'Placid', 'Attila'] },
	{ date: { month: 'Október', days: 6 }, names: ['Brúnó', 'Renáta', 'Renátó'] },
	{ date: { month: 'Október', days: 7 }, names: ['Amália', 'Bekény'] },
	{ date: { month: 'Október', days: 8 }, names: ['Koppány', 'Benedikta'] },
	{ date: { month: 'Október', days: 9 }, names: ['Dénes', 'János'] },
	{ date: { month: 'Október', days: 10 }, names: ['Gedeon', 'Ferenc', 'Bendegúz'] },
	{ date: { month: 'Október', days: 11 }, names: ['Brigitta', 'Placida', 'Etel', 'Gitta'] },
	{ date: { month: 'Október', days: 12 }, names: ['Miksa', 'Rezső', 'Edvin'] },
	{ date: { month: 'Október', days: 13 }, names: ['Kálmán', 'Ede', 'Edvárd'] },
	{ date: { month: 'Október', days: 14 }, names: ['Helén', 'Kaldixtusz'] },
	{ date: { month: 'Október', days: 15 }, names: ['Teréz', 'Aranka'] },
	{ date: { month: 'Október', days: 16 }, names: ['Gál', 'Margit', 'Hedvig'] },
	{ date: { month: 'Október', days: 17 }, names: ['Hedvig', 'Ignác', 'Rudolf'] },
	{ date: { month: 'Október', days: 18 }, names: ['Lukács', 'Jusztusz'] },
	{ date: { month: 'Október', days: 19 }, names: ['Nándor', 'János', 'Pál'] },
	{ date: { month: 'Október', days: 20 }, names: ['Vendel', 'Irén', 'Kleopátra'] },
	{ date: { month: 'Október', days: 21 }, names: ['Orsolya', 'Zsolt'] },
	{ date: { month: 'Október', days: 22 }, names: ['Előd', 'Szalóme', 'Kordélia'] },
	{ date: { month: 'Október', days: 23 }, names: ['Gyöngyvér', 'János', 'Gyöngyi'] },
	{ date: { month: 'Október', days: 24 }, names: ['Salamon', 'Antal'] },
	{ date: { month: 'Október', days: 25 }, names: ['Blanka', 'Bianka', 'Beniel', 'Mór'] },
	{ date: { month: 'Október', days: 26 }, names: ['Dömötör', 'Armand', 'Örs'] },
	{ date: { month: 'Október', days: 27 }, names: ['Szabina', 'Antonietta'] },
	{ date: { month: 'Október', days: 28 }, names: ['Simon', 'Szimonetta', 'Szimóna', 'Júdás', 'Tádé'] },
	{ date: { month: 'Október', days: 29 }, names: ['Nárcisz', 'Melinda', 'Őzike'] },
	{ date: { month: 'Október', days: 30 }, names: ['Alfonz', 'Zenóbia'] },
	{ date: { month: 'Október', days: 31 }, names: ['Farkas', 'Rodrigó', 'Wolfgang'] },

	// November
	{ date: { month: 'November', days: 1 }, names: ['Marianna'] },
	{ date: { month: 'November', days: 2 }, names: ['Achilles', 'Bató'] },
	{ date: { month: 'November', days: 3 }, names: ['Győző', 'Márton'] },
	{ date: { month: 'November', days: 4 }, names: ['Károly', 'Karola'] },
	{ date: { month: 'November', days: 5 }, names: ['Imre', 'Zakariás', 'Tétény'] },
	{ date: { month: 'November', days: 6 }, names: ['Lénárd'] },
	{ date: { month: 'November', days: 7 }, names: ['Csenger', 'Rezső', 'Ernő', 'Florentin'] },
	{ date: { month: 'November', days: 8 }, names: ['Zsombor', 'Kolos', 'Gottfrid'] },
	{ date: { month: 'November', days: 9 }, names: ['Tivadar'] },
	{ date: { month: 'November', days: 10 }, names: ['Réka', 'András', 'Leó'] },
	{ date: { month: 'November', days: 11 }, names: ['Márton', 'Atád', 'Tódor'] },
	{ date: { month: 'November', days: 12 }, names: ['Jónás', 'Renátó', 'Jozafát'] },
	{ date: { month: 'November', days: 13 }, names: ['Szilvia', 'Szaniszló'] },
	{ date: { month: 'November', days: 14 }, names: ['Aliz', 'Vanda', 'Huba', 'Klementina'] },
	{ date: { month: 'November', days: 15 }, names: ['Albert', 'Lipót'] },
	{ date: { month: 'November', days: 16 }, names: ['Ödön', 'Margit'] },
	{ date: { month: 'November', days: 17 }, names: ['Hortenzia', 'Gergő', 'Dénes'] },
	{ date: { month: 'November', days: 18 }, names: ['Jenő', 'Noé'] },
	{ date: { month: 'November', days: 19 }, names: ['Erzsébet', 'Zsóka'] },
	{ date: { month: 'November', days: 20 }, names: ['Jolán', 'Zsolt', 'Ödön', 'Bódog'] },
	{ date: { month: 'November', days: 21 }, names: ['Olivér'] },
	{ date: { month: 'November', days: 22 }, names: ['Cecília', 'Filemon'] },
	{ date: { month: 'November', days: 23 }, names: ['Kelemen', 'Klementina', 'Kolumbán'] },
	{ date: { month: 'November', days: 24 }, names: ['Emma', 'Flóra', 'Virág', 'Emmaróza'] },
	{ date: { month: 'November', days: 25 }, names: ['Katalin', 'Liza', 'Katinka'] },
	{ date: { month: 'November', days: 26 }, names: ['Virág', 'Szvetlana', 'Konrád', 'Viktória', 'Milos'] },
	{ date: { month: 'November', days: 27 }, names: ['Virgil', 'Virgínia'] },
	{ date: { month: 'November', days: 28 }, names: ['Stefánia', 'Jakab'] },
	{ date: { month: 'November', days: 29 }, names: ['Taksony', 'Ilma', 'Filoména'] },
	{ date: { month: 'November', days: 30 }, names: ['András', 'Andor', 'Andrea'] },

	// December
	{ date: { month: 'December', days: 1 }, names: ['Elza', 'Natália', 'Blanka', 'Bonita'] },
	{ date: { month: 'December', days: 2 }, names: ['Melinda', 'Vivien', 'Aranka'] },
	{ date: { month: 'December', days: 3 }, names: ['Ferenc', 'Olívia'] },
	{ date: { month: 'December', days: 4 }, names: ['Borbála', 'Barbara', 'János'] },
	{ date: { month: 'December', days: 5 }, names: ['Vilma', 'Ünige', 'Csaba'] },
	{ date: { month: 'December', days: 6 }, names: ['Miklós', 'Csinszka', 'Gyopár', 'Gyopárka'] },
	{ date: { month: 'December', days: 7 }, names: ['Ambrus', 'Ambrózia'] },
	{ date: { month: 'December', days: 8 }, names: ['Mária', 'Emőke'] },
	{ date: { month: 'December', days: 9 }, names: ['Natália', 'Valéria', 'Filótea'] },
	{ date: { month: 'December', days: 10 }, names: ['Judit', 'Loretta', 'Eulália'] },
	{ date: { month: 'December', days: 11 }, names: ['Árpád', 'Árpádina', 'Damazusz'] },
	{ date: { month: 'December', days: 12 }, names: ['Gabriella', 'Johanna', 'Franciska'] },
	{ date: { month: 'December', days: 13 }, names: ['Luca', 'Otília', 'Lúcia', 'Éda', 'Tilia'] },
	{ date: { month: 'December', days: 14 }, names: ['Szilárda', 'Szilárd', 'János'] },
	{ date: { month: 'December', days: 15 }, names: ['Valér', 'Detre'] },
	{ date: { month: 'December', days: 16 }, names: ['Etelka', 'Aletta', 'Adelaida'] },
	{ date: { month: 'December', days: 17 }, names: ['Lázár', 'Olimpia'] },
	{ date: { month: 'December', days: 18 }, names: ['Auguszta', 'Gracián'] },
	{ date: { month: 'December', days: 19 }, names: ['Viola', 'Anasztáz'] },
	{ date: { month: 'December', days: 20 }, names: ['Teofil', 'Liberátusz'] },
	{ date: { month: 'December', days: 21 }, names: ['Tamás', 'Péter'] },
	{ date: { month: 'December', days: 22 }, names: ['Zénó', 'Flórián'] },
	{ date: { month: 'December', days: 23 }, names: ['Viktória', 'János'] },
	{ date: { month: 'December', days: 24 }, names: ['Ádám', 'Éva', 'Adél', 'Noé'] },
	{ date: { month: 'December', days: 25 }, names: ['Eugénia', 'Anasztázia'] },
	{ date: { month: 'December', days: 26 }, names: ['István'] },
	{ date: { month: 'December', days: 27 }, names: ['János', 'Teodor'] },
	{ date: { month: 'December', days: 28 }, names: ['Kamilla', 'Apor'] },
	{ date: { month: 'December', days: 29 }, names: ['Tamás', 'Tamara'] },
	{ date: { month: 'December', days: 30 }, names: ['Dávid', 'Hunor', 'Libériusz'] },
	{ date: { month: 'December', days: 31 }, names: ['Szilveszter', 'Donáta'] },
]

/**
 * Visszaadja a megadott dátumon lévő névnapokat
 * @param date A kiválasztott dátum
 * @returns Az adott dátumon lévő névnapok
 */
export function getNameDay(date: Date): Array<string> {
	const month = getMonthName(date)

	// Ha szökőév van
	if (isLeapYear(date.getFullYear())) {
		//február, és a dátum nagyobb egyenlő 24 akkor az előző napi névnapok aktuálisak, 24. nincs
		if (month === 'Február' && date.getDate() >= 24) {
			// 24. van, nincs névnap
			if (date.getDate() === 24) {
				return []
			}
			// Több mint 24, az előző napi névnapokat kérjük el
			else {
				date.setDate(date.getDate() - 1)
			}
		}
	}

	const foundNameDay = NAME_DAYS.find((nameDay) => nameDay.date.days === date.getDate() && nameDay.date.month === month) as INameDay

	return foundNameDay.names
}
