// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calendar-container': string;
  'calendar-days-container': string;
  'calendar-header': string;
  'calendar-nav': string;
  'month': string;
  'sunday': string;
  'weekday-name': string;
  'year': string;
}
export const cssExports: CssExports
export default cssExports
