// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calendar-day': string;
  'calendar-empty-day': string;
  'day': string;
  'holiday': string;
  'material-icons': string;
  'weekend': string;
}
export const cssExports: CssExports
export default cssExports
